#Redis Configuration
spring:
  data:
    redis:
      host : localhost
      port : 6379
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sunro
    password: leesunro12
    url: jdbc:mysql://localhost:3306/redisTest?serverTimezone=Asia/Seoul


  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

